# Generated by Django 2.1.7 on 2019-03-05 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('note_utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('rowinformation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='note_utils.RowInformation')),
                ('title', models.CharField(max_length=256)),
                ('text', models.TextField(verbose_name='Put in your notes here')),
            ],
            options={
                'verbose_name_plural': 'Notes',
            },
            bases=('note_utils.rowinformation',),
        ),
    ]
